
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dbsys.AppData
{

using System;
    using System.Collections.Generic;
    
public partial class Ticket
{

    public int TicketNo { get; set; }

    public string MovieTitle { get; set; }

    public Nullable<System.DateTime> ShowingDate { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<decimal> TotalAmount { get; set; }

}

}
