
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dbsys.AppData
{

using System;
    using System.Collections.Generic;
    
public partial class UserInformation
{

    public int MenuNo { get; set; }

    public string Description { get; set; }

    public string CustomerName { get; set; }

    public Nullable<int> ContactNo { get; set; }

    public Nullable<int> EmailAddress { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<decimal> TotalSales { get; set; }

    public Nullable<int> userId { get; set; }



    public virtual UserAccount UserAccount { get; set; }

}

}
